include:
  - https://gitlab.com/wrzlbrmft/gitlab-ci/-/raw/main/dockerize.yml

variables:
  ARTIFACT: tinyproxy

stages:
  - dockerize

dockerize:
  extends: .dockerize-no-git
  services:
    - docker:20-dind
