variables:
  ARTIFACT: tinyproxy

stages:
  - dockerize

dockerize:
  stage: dockerize
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/$ARTIFACT
    TAG: latest
  image: docker:20
  services:
    - docker:20-dind
  before_script:
    - echo -n ${CI_REGISTRY_PASSWORD} | docker login --username ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
  script:
    - docker pull ${IMAGE}:${TAG} || true
    - >
      docker build
      --tag ${IMAGE}:${TAG}
      --cache-from ${IMAGE}:${TAG}
      --network host
      .
    - docker push ${IMAGE}:${TAG}
    - docker rmi -f $(docker images ${IMAGE} -q) || true
